## FIRST WORKSPACE

.PHONY: sync-first-workspace
sync-first-workspace:
	cd first-workspace/ && deck sync --config deck.yaml --parallelism 1 # IMPORTANT WHEN USING CASSANDRA

## SECOND WORKSPACE

.PHONY: sync-second-workspace
sync-second-workspace:
	cd second-workspace/ && deck sync --config deck.yaml --parallelism 1 # IMPORTANT WHEN USING CASSANDRA

## THIRD WORKSPACE

.PHONY: sync-third-workspace
sync-third-workspace:
	cd third-workspace/ && deck sync --config deck.yaml --parallelism 1 # IMPORTANT WHEN USING CASSANDRA