## FIRST WORKSPACE

.PHONY: enable-first-workspace
enable-first-workspace:
	portal enable first-workspace

.PHONY: fetch-first-workspace
fetch-first-workspace:
	portal fetch first-workspace

.PHONY: deploy-first-workspace
deploy-first-workspace:
	portal deploy first-workspace --preserve

.PHONY: disable-first-workspace
disable-first-workspace:
	portal wipe first-workspace && portal disable first-workspace


## SECOND WORKSPACE

.PHONY: enable-second-workspace
enable-second-workspace:
	portal enable second-workspace

.PHONY: fetch-second-workspace
fetch-second-workspace:
	portal fetch second-workspace

.PHONY: deploy-second-workspace
deploy-second-workspace:
	portal deploy second-workspace --preserve

.PHONY: disable-second-workspace
disable-second-workspace:
	portal wipe second-workspace && portal disable second-workspace

## THIRD WORKSPACE

.PHONY: enable-third-workspace
enable-third-workspace:
	portal enable third-workspace

.PHONY: fetch-third-workspace
fetch-third-workspace:
	portal fetch third-workspace

.PHONY: deploy-third-workspace
deploy-third-workspace:
	portal deploy third-workspace --preserve

.PHONY: disable-third-workspace
disable-third-workspace:
	portal wipe third-workspace && portal disable third-workspace